
--- This SQL script is generated by ChateGPT with help of datamodels.png images



-- =========================================
-- CREATE SCHEMA
-- =========================================

CREATE SCHEMA IF NOT EXISTS raw;

USE raw;


-- =========================================
-- 1. CUSTOMERS
-- =========================================

CREATE TABLE customers (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(255),
    phone_number VARCHAR(20),
    date_joined DATE
);


-- =========================================
-- 2. STORE BRANCH
-- =========================================

CREATE TABLE store_branch (
    store_branch_id INT AUTO_INCREMENT PRIMARY KEY,
    store_branch_name VARCHAR(150),
    store_branch_locations VARCHAR(255)
);


-- =========================================
-- 3. PRODUCTS
-- =========================================

CREATE TABLE products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(255),
    category_id INT,
    price DECIMAL(10,2),
    stock_qty INT
);


-- =========================================
-- 4. ORDERS
-- =========================================

CREATE TABLE orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    total_amount DECIMAL(10,2),
    store_branch_id INT,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_orders_store_branch
        FOREIGN KEY (store_branch_id)
        REFERENCES store_branch(store_branch_id)
);


-- =========================================
-- 5. ORDER ITEMS
-- =========================================

CREATE TABLE orders_items (
    order_items_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    product_id INT,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);


-- =========================================
-- 6. PAYMENTS
-- =========================================

CREATE TABLE payments (
    payment_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    payment_methods VARCHAR(50),
    payment_amount DECIMAL(10,2),
    payment_status VARCHAR(50),
    transaction_status VARCHAR(50),

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);


-- =========================================
-- 7. SHIPMENTS
-- =========================================

CREATE TABLE shipments (
    shipment_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    shipping_carries VARCHAR(100),
    tracking_number VARCHAR(100),
    shipments_status VARCHAR(50),
    estimated_delivery_date DATE,

    CONSTRAINT fk_shipments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);